### ISSUE TITLE
EXE Setup

### ISSUE THREAD

**Issue by Joaolendo** [Freenex1911/Unturned-Uconomy-Utility#1]
You have the Unturned Uconomy Utility.exe? Impossible to find :\

**Comment by zadexo** [comment]
https://drive.google.com/open?id=1xSLVZS1mEhqyAvmj9IYcg7L8xJ06eLLa

**Comment by Freenex1911** [comment]
https://github.com/Freenex1911/Unturned-Uconomy-Utility/releases
