### ISSUE TITLE
Unturned Uconomy Utility.exe

### ISSUE THREAD

**Issue by Chingiz51464** [Freenex1911/Unturned-Uconomy-Utility#2]
Hi! I can't open this utility because there is no file (exe) Do you have a missing file? Where to download? or how to run. The fact is that I configure the plugin (economy) for the game Unturned. I have not found (UUU) except you please

**Comment by Freenex1911** [comment]
https://github.com/Freenex1911/Unturned-Uconomy-Utility/releases

Assets >

**Comment by AlexNTFox** [comment]
any approximate release date? Maybe you can share old versions?

**Comment by Reytholian** [comment]
Nothing shows up at all. I know I've used your program before but this is the only place to download which has no executable file to run it nowadays.

**Comment by Freenex1911** [comment]
It's now available.

https://github.com/Freenex1911/Unturned-Uconomy-Utility/releases/
