### ISSUE TITLE
i cant open unturned uconomy utility

### ISSUE THREAD

**Issue by ghost** [Freenex1911/Unturned-Uconomy-Utility#3]
when i open unturned uconomy utility it crashes automatically only on my windows server
servers specs are
Windows Server 2012 R2
i9 9900K
3GB RAM
.net framework 4.6 installed

i can use appserv's mysql but that one uses alot of ram so i use unicontroller's mysql and i cant reach unicontroller's mysql on my own pc

**Comment by Freenex1911** [comment]
Please take a look at the `Event Viewer` on Windows and send me the error.

**Comment by ghost** [comment]
http://prntscr.com/rg8xgu where from here

**Comment by Freenex1911** [comment]
Özel Görünümümümü -> Administrative Events

**Comment by ghost** [comment]
http://prntscr.com/rg8yhy

**Comment by Freenex1911** [comment]
I need the error message...

**Comment by Erkan53** [comment]
where do i access that

**Comment by ghost** [comment]
Application Error


Hatalı uygulama adı: Unturned.Uconomy.Utility.exe, sürüm: 1.0.0.0, zaman damgası: 0x59bd1261
Hatalı modül adı: KERNELBASE.dll, sürüm: 6.3.9600.17031, zaman damgası: 0x53089862
Özel durum kodu: 0xe0434352
Hata uzaklığı 0x00000000000068d8
Hatalı işlem kimliği: 0x15ec
Uygulama başlangıç zamanı: 0x01d5f9fca6ee3d81
Hatalı uygulama yolu: C:\Users\Administrator\Desktop\Unturned.Uconomy.Utility.exe
Hatalı modül yolu: C:\Windows\system32\KERNELBASE.dll
Rapor kimliği: e4cac2cb-65ef-11ea-80c9-00505682357b
Hatalı paket tam adı: 
Hatalı paketle ilgili uygulama kimliği:

**Comment by ghost** [comment]
.NET Runtime

Uygulama: Unturned.Uconomy.Utility.exe
Framework Sürümü: v4.0.30319
Açıklama: İşlenmeyen bir özel durum nedeniyle işlem sonlandırıldı.
Özel Durum Bilgisi: System.Net.Sockets.SocketException
   konum: System.Net.Sockets.NetworkStream.Read(Byte[], Int32, Int32)

Özel Durum Bilgisi: System.IO.IOException
   konum: System.Net.Sockets.NetworkStream.Read(Byte[], Int32, Int32)
   konum: System.Net.PooledStream.Read(Byte[], Int32, Int32)
   konum: System.Net.Connection.SyncRead(System.Net.HttpWebRequest, Boolean, Boolean)

Özel Durum Bilgisi: System.Net.WebException
   konum: System.Net.WebClient.DownloadDataInternal(System.Uri, System.Net.WebRequest ByRef)
   konum: System.Net.WebClient.DownloadString(System.Uri)
   konum: Unturned_Uconomy_Utility.frmMain..ctor()
   konum: Unturned_Uconomy_Utility.classMain.Main()

**Comment by Freenex1911** [comment]
Seems like your server has trouble downloading the items/vehicles from pastebin. I can't tell why tho from what you sent me. I can run the UUU with .NET 4.8 just fine. The application is build for .NET 4.5.

**Comment by Erkan53** [comment]
weird

**Comment by ghost** [comment]
uh oh seems like pastebin is banned in my country ( DONT KNOW WHY )
http://prntscr.com/rg93yo
well also i can run this program on my pc without any problems (item ids doesnt list tho)
is there any chance you can make a hastebin version of this i really need it thanks

**Comment by ghost** [comment]
@Freenex1911 are you going to do it ?

**Comment by Freenex1911** [comment]
Feel free to add a PR or unblock pastebin with custom DNS entries.

**Comment by ghost** [comment]
i cant add custom dns its disabled on my hosting provider and there is no way to enable it

**Comment by Freenex1911** [comment]
I'm sorry to say that but this isn't UUU's fault.

> 
> 
> **Feel free to add a PR** or unblock pastebin with custom DNS entries.
