### ISSUE TITLE
UUU Crashes when attempting to access remote MySQL Community Database

### ISSUE THREAD

**Issue by Orangian** [Freenex1911/Unturned-Uconomy-Utility#4]
Hi. I run MySQL Community Edition on my Ubuntu server and whenever I attempt to access it remotely with UUU I get the following error: https://pastebin.com/KQXGaAQT
Even if I hit continue it still does not connect. I have double-checked all of the information there and it is all correct. Do you know what the issue might be? Thanks for any help possible.

**Comment by Freenex1911** [comment]
Please try to run the program on another computer and make sure to install .NET 4.5.

**Comment by Orangian** [comment]
Hi. I tried to install .NET Framework 4.5 on both computers, however, they already had it installed. Unfortunately, I got a similar error on my laptop. Here is the log: https://pastebin.com/PjD9Bjan Could it be that something is wrong with the server itself? Thanks for any help possible.

**Comment by Freenex1911** [comment]
Try to disable TLS.
https://stackoverflow.com/questions/37925505/

**Comment by Orangian** [comment]
I think I disabled TLS by writing skip_ssl in my mysqld.cnf file, however, now I am getting the error "Authentication method 'caching_sha2_password' not supported by any of the available plugins." Did I correctly do what you asked or should I have done something else?

**Comment by Freenex1911** [comment]
You might have to use legacy authentication:
https://stackoverflow.com/a/54683556/12144193

**Comment by Orangian** [comment]
Thanks, that worked! It was a bit different on Ubuntu Server, what I had to do was append

[mysqld]
default_authentication_plugin = mysql_native_password

at the end of /etc/mysql/my.cnf but UUU works now. Thanks for the help!
