### ISSUE TITLE
The calling to SSPI failed

### ISSUE THREAD

**Issue by setpopa** [Freenex1911/Unturned-Uconomy-Utility#8]
guys im stil getting this error when i connecting whatever i do : 

v System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   v System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   v System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   v System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   v System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   v System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   v System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   v MySql.Data.MySqlClient.NativeDriver.StartSSL()
   v MySql.Data.MySqlClient.NativeDriver.Open()
   v MySql.Data.MySqlClient.Driver.Open()
   v MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   v MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   v MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   v MySql.Data.MySqlClient.MySqlPool.GetConnection()
   v MySql.Data.MySqlClient.MySqlConnection.Open()
   v Unturned_Uconomy_Utility.frmDatabase.btnConnect_Click(Object sender, EventArgs e)
   v System.Windows.Forms.Control.OnClick(EventArgs e)
   v System.Windows.Forms.Button.OnClick(EventArgs e)
   v System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   v System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   v System.Windows.Forms.Control.WndProc(Message& m)
   v System.Windows.Forms.ButtonBase.WndProc(Message& m)
   v System.Windows.Forms.Button.WndProc(Message& m)
   v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

im connecting remotly but when i use heidisql i connected fine

**Comment by Freenex1911** [comment]
This is only the stack trace. Please send me the full error message above the trace.

**Comment by setpopa** [comment]
I translated it so it can be little bit different. 

System.Security.Authentication.AuthenticationException: SSPI call failed. See internal exception. ---> System.ComponentModel.Win32Exception: The requested function is not supported

************** Načtená sestavení **************
mscorlib
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Unturned Uconomy Utility
    Verze sestavení: 1.0.0.0
    Verze Win32: 1.0.0.0
    Základ kódu (CodeBase): file:///C:/Users/Acer%20Swift/Downloads/Unturned.Uconomy.Utility.exe
----------------------------------------
System.Windows.Forms
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4360.0 built by: NET48REL1LAST_C
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MySql.Data
    Verze sestavení: 6.9.8.0
    Verze Win32: 1.0.0.0
    Základ kódu (CodeBase): file:///C:/Users/Acer%20Swift/Downloads/Unturned.Uconomy.Utility.exe
----------------------------------------
System.Configuration
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4084.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4270.0 built by: NET48REL1LAST_C
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4084.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
mscorlib.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4084.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.EnterpriseServices
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4084.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4084.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.4084.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

**Comment by Freenex1911** [comment]
Doesn't matter what I do, I cannot replicate your problem. Could you try to use my tool on another computer just to see if that makes any difference?

**Comment by setpopa** [comment]
Man im not home(i will be home in 5 day and this my only computer here ) but maybe someone from my friends can do it for me. 

I'll get back to you when I get home or when I hear from one of my friends.

**Comment by setpopa** [comment]
So i'm back and it look like on other computer it is not make any change.

**Comment by setpopa** [comment]
So I solved it by first disabling ssl by typing skip_ssl under [mysqld] in /etc/mysql/my.cnf (then restart mysql).Then i changed my unturned user to use the mysql_native_password plugin instead of caching_sha2_password so i run this command to mysql wiht root: 

ALTER USER 'youruser'@'yourhostname' IDENTIFIED WITH mysql_native_password BY 'yourcurrentpassword';

yourhostname is most of the time % if you using remote access
